local config = {
	thing = "this is a config thing",
	CAM_WIDTH = 800,
	CAM_HEIGHT = 600,
	WORLD_WIDTH = 1200,
	WORLD_HEIGHT = 1000,
	COLORS = {
		White = { 1, 1, 1, 1 },
		Green = { 0.486, 0.988, 0, 1 },
		Red = { 0.769, 0.125, 0.125, 1 },
		Amber = { 0.902, 0.671, 0.082, 1 },
	},
	WHITE = { 1, 1, 1 },
	GREEN = { 0.486, 0.988, 0 },
	RED = { 0.769, 0.125, 0.125 },
	AMBER = { 0.902, 0.671, 0.082 },

	PLANETNAMES = {
		"Aurora Nexus",
		"Cygnus Expanse",
		"Draconis-7",
		"Andromeda Rift",
		"Seraphis Cluster",
		"Phoenix-12",
		"Erebus",
		"Helios Prime",
		"Vega Parallax",
		"Lyra Continuum",
		"Epsilon Drift",
		"Orion's Gate",
		"Centauri-3",
		"Zenith Cascade",
		"Arcturus Halo",
		"Neptune-6",
		"Alphard",
		"Scorpius Frontier",
		"Nova Cradle",
		"Quasar-14",
		"Proxima",
		"Polaris-1",
		"Titanium Horizon",
		"Vespera",
		"Aetheria",
		"Sirius-9",
		"Galatea",
		"Typhon Rift",
		"Cetus",
		"Nyx Ascendancy",
		"Hydra-2",
		"Rigel Nexus",
		"Selene's Veil",
		"Tartarus",
		"Xenon Verge",
		"Cygnet",
		"Solis Cradle",
		"Pleiades-8",
		"Arcadia",
		"Eidolon Spiral",
		"Noctis-11",
		"Antares Halo",
		"Dione's Forge",
		"Tempest Outlands",
		"Miranda",
		"Zephyr Cascade",
		"Vulcan",
		"Nyriad Expanse",
		"Astron",
		"Helion Dominion",
		"Phoenix Gate",
		"Auriga Fringe",
		"Ymir",
		"Alcor Traverse",
		"Taurus Outback",
		"Obsidian",
		"Xanadu Realm",
		"Galaxis-7",
		"Thalassa",
		"Charon Conflux",
		"Vega's Rest",
		"Odyssey Array",
		"Abydos Cradle",
		"Cassiopeia-5",
		"Hyperion Sector",
		"Thanatos",
		"Oberon Horizon",
		"Altair Belt",
		"Nebulon",
		"Aquila Domain",
		"Spica's Arc",
		"Yggdrasil",
		"Kronos Spiral",
		"Selas",
		"Eridani Reach",
		"Zeta Cascade",
		"Viridian",
		"Morpheus",
		"Vega's Ring",
		"Tethys",
		"Daedalus Halo",
		"Lucida",
		"Praxia Cluster",
		"Astara",
		"Lycan Spiral",
		"Zenith",
		"Ceres Outpost",
		"Nebula Nexus",
		"Trinity",
		"Galatea Cascade",
		"Raven",
		"Auriga's Cross",
		"Solstice",
		"Nephthys Veil",
		"Aurelia",
		"Xenith Passage",
		"Valhalla Rift",
		"Alcyon",
		"Spectra Expanse",
		"Argo Nexus",
		"Helios Domain",
		"Saphira",
		"Quanta Verge",
		"Cygni",
		"Triton Nexus",
		"Celestia Halo",
		"Nyx Dominion",
		"Eos",
		"Vega's Anomaly",
		"Solis Haven",
		"Orion's Reach",
		"Hyperion Abyss",
		"Atropos",
		"Nova's Edge",
		"Equinox Rift",
		"Icarus",
		"Anthelion Sector",
		"Astral Cascade",
		"Thalassa Gate",
		"Exodus",
		"Aurelius",
		"Serena",
		"Echo Verge",
		"Styx",
		"Astraea Cluster",
		"Erebus",
		"Phaeton Horizon",
		"Arcadian Passage",
		"Vespera",
		"Chimera",
		"Lyra's Rest",
		"Arcane Nexus",
		"Zenith",
		"Atlas Belt",
		"Valkyrie",
		"Spectre Verge",
		"Empyrean",
		"Nexus",
		"Lunar Cradle",
		"Scylla",
		"Elysium",
		"Seraphim",
		"Valerian Rift",
		"Stellar",
		"Eclipse",
		"Centaurus",
		"Astrid",
		"Vortex",
		"Thanatos",
		"Rhea",
		"Chronos",
		"Arcadia",
		"Nova Haven",
		"Odysseus",
		"Nereus Horizon",
		"Prometheus",
		"Sirius",
		"Ascendant",
		"Exo",
		"Tartarus",
		"Lunaris",
		"Aether",
		"Eidolon",
		"Phantom",
		"Helion",
		"Titan",
		"Thalassa",
		"Oblivion",
		"Abyssus",
		"Astraea",
		"Exoria",
		"Epsilon",
		"Artemis",
		"Solstice",
		"Orion",
		"Aetherium",
		"Pallas",
		"Zion",
		"Quasar",
		"Vega",
		"Omega",
		"Rapture",
		"Celestial",
		"Horizon",
		"Obsidian",
		"Vanguard",
		"Aurora",
		"Astral",
		"Helios",
		"Xenon",
		"Gaea",
		"Echoes",
		"Olympus",
		"Nemesis",
		"Nyriad",
	},
}
return config
